/**
 * SmartCart Fashion AI - Multi-Brand Master Dataset
 * 44+ premium fashion items across 4 core categories from top global brands
 */

export const INITIAL_PRODUCTS = [
  // ==========================================
  // 1. SHIRTS & TOPS (11 Products)
  // ==========================================
  {
    id: "top-01",
    brand: "Ralph Lauren",
    name: "Polo Ralph Lauren Classic Oxford Shirt",
    category: "tops",
    price: 98.50,
    unit: "each",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 320,
    stock: 25,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sky Blue", "Crisp White", "Soft Pink"],
    styles: ["smart_casual", "formal"],
    material: "100% Breathable Pinpoint Cotton",
    description: "Iconic button-down collar Oxford shirt with signature embroidered pony on left chest."
  },
  {
    id: "top-02",
    brand: "Nike",
    name: "Nike Club Fleece Heavyweight Pullover Hoodie",
    category: "tops",
    price: 65.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 410,
    stock: 35,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal Heather", "Midnight Navy", "Black"],
    styles: ["streetwear", "athletic"],
    material: "80% Cotton, 20% Brushed Polyester Fleece",
    description: "Classic streetwear hoodie combining soft brushed-back fleece with ribbed cuffs and adjustable drawstring hood."
  },
  {
    id: "top-03",
    brand: "Zara",
    name: "Zara Tailored French Linen Casual Shirt",
    category: "tops",
    price: 49.90,
    unit: "each",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    reviews: 185,
    stock: 22,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sage Olive", "Sand Beige", "Optic White"],
    styles: ["smart_casual", "sustainable"],
    material: "100% French Flax Linen",
    description: "Relaxed resort-collar linen shirt designed for warm evenings, beach getaways, and smart layering."
  },
  {
    id: "top-04",
    brand: "Levi's",
    name: "Levi's Vintage Fit Selvedge Denim Trucker Jacket",
    category: "tops",
    price: 118.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 280,
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dark Stonewash Indigo", "Washed Black"],
    styles: ["streetwear", "smart_casual"],
    material: "100% Heavyweight Rigid Cotton Denim",
    description: "The original denim jacket since 1967 with vintage brass shank buttons and chest patch pockets."
  },
  {
    id: "top-05",
    brand: "Uniqlo",
    name: "Uniqlo Supima Cotton Crewneck Essential Tee",
    category: "tops",
    price: 24.90,
    unit: "each",
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 530,
    stock: 60,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Jet Black", "Optic White", "Muted Olive", "Navy"],
    styles: ["sustainable", "streetwear", "smart_casual"],
    material: "100% Extra-Long Staple Supima Cotton",
    description: "Ultra-clean minimalist t-shirt with silky smooth texture and long-lasting color retention."
  },
  {
    id: "top-06",
    brand: "Patagonia",
    name: "Patagonia Better Sweater 1/4-Zip Fleece",
    category: "tops",
    price: 139.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 195,
    stock: 14,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Oatmeal Heather", "Stonewash Grey", "Black"],
    styles: ["sustainable", "smart_casual"],
    material: "100% Recycled Polyester Sweater-Knit Fleece",
    description: "Fair Trade Certified warm pullover sweater combining a sweater-knit aesthetic with easy-care fleece."
  },
  {
    id: "top-07",
    brand: "Tommy Hilfiger",
    name: "Tommy Hilfiger Classic Custom-Fit Piqué Polo",
    category: "tops",
    price: 79.50,
    unit: "each",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 140,
    stock: 26,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy Blue", "Crimson Red", "Bright White"],
    styles: ["smart_casual", "formal"],
    material: "100% Organic Breathable Cotton Piqué",
    description: "Signature polo shirt featuring the iconic flag embroidery on chest and rib-knit collar."
  },
  {
    id: "top-08",
    brand: "Carhartt WIP",
    name: "Carhartt WIP Chase Heavyweight Graphic Tee",
    category: "tops",
    price: 45.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 210,
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Eucalyptus Green", "Black", "Off-White"],
    styles: ["streetwear"],
    material: "235 GSM Combed Cotton Jersey",
    description: "Durable workwear-inspired streetwear t-shirt with gold 'C' logo embroidery."
  },
  {
    id: "top-09",
    brand: "Lululemon",
    name: "Lululemon Metal Vent Tech Athletic Workout Top",
    category: "tops",
    price: 78.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 310,
    stock: 28,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Slate Grey", "Electric Blue", "Matte Black"],
    styles: ["athletic"],
    material: "Silverescent Anti-Odor Recycled Nylon",
    description: "Seamless performance training top powered by anti-stink Silverescent yarn technology."
  },
  {
    id: "top-10",
    brand: "Calvin Klein",
    name: "Calvin Klein Modern Stretch Cotton Dress Shirt",
    category: "tops",
    price: 85.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1620012253295-c15c429f6d7d?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    reviews: 165,
    stock: 20,
    sizes: ["15.5 (M)", "16.5 (L)", "17.5 (XL)"],
    colors: ["Classic White", "Midnight Black", "Steel Grey"],
    styles: ["formal", "smart_casual"],
    material: "96% Supima Cotton, 4% Elastane",
    description: "Crisp tailored dress shirt with subtle stretch for flawless all-day silhouette and movement."
  },
  {
    id: "top-11",
    brand: "H&M",
    name: "H&M Edition Relaxed Linen Blend Overshirt",
    category: "tops",
    price: 42.99,
    unit: "each",
    image: "https://images.unsplash.com/photo-1563630423918-b58f07336ac9?auto=format&fit=crop&w=500&q=80",
    rating: 4.6,
    reviews: 130,
    stock: 35,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Khaki Green", "Washed Beige"],
    styles: ["smart_casual", "streetwear"],
    material: "55% Linen, 45% Organic Cotton",
    description: "Contemporary boxy overshirt with dual front utility flap pockets."
  },

  // ==========================================
  // 2. JEANS & PANTS (11 Products)
  // ==========================================
  {
    id: "bottom-01",
    brand: "Levi's",
    name: "Levi's 501 Original Fit Selvedge Denim Jeans",
    category: "bottoms",
    price: 98.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 620,
    stock: 30,
    sizes: ["30x30", "32x32", "34x32", "36x34"],
    colors: ["Medium Indigo", "Raw Dark Stonewash", "Washed Black"],
    styles: ["streetwear", "smart_casual"],
    material: "100% Heavyweight Selvedge Cotton",
    description: "The timeless blueprint for all denim jeans since 1873 with signature straight leg and button fly."
  },
  {
    id: "bottom-02",
    brand: "Lululemon",
    name: "Lululemon ABC Classic-Fit Stretch Trouser",
    category: "bottoms",
    price: 128.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=500&q=80",
    rating: 5.0,
    reviews: 450,
    stock: 25,
    sizes: ["30x30", "32x32", "34x32", "36x32"],
    colors: ["Obsidian Black", "Trench Tan", "Navy", "Dark Olive"],
    styles: ["smart_casual", "formal", "athletic"],
    material: "Warpstreme Four-Way Stretch Fabric",
    description: "Everyday luxury performance pants featuring ergonomic ABC (Anti-Ball-Crushing) gusset design."
  },
  {
    id: "bottom-03",
    brand: "Wrangler",
    name: "Wrangler Retro Slim Straight Leg Jeans",
    category: "bottoms",
    price: 69.99,
    unit: "each",
    image: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    reviews: 195,
    stock: 24,
    sizes: ["30x32", "32x32", "34x32", "36x32"],
    colors: ["River Rock Dark Wash", "Vintage Tint"],
    styles: ["streetwear", "smart_casual"],
    material: "99% Cotton, 1% Spandex Comfort Denim",
    description: "Classic Western heritage jeans with 'W' stitched back pockets and tailored slim straight leg."
  },
  {
    id: "bottom-04",
    brand: "Dockers",
    name: "Dockers Signature Iron-Free Slim Fit Chinos",
    category: "bottoms",
    price: 58.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 290,
    stock: 35,
    sizes: ["30x30", "32x32", "34x32", "36x32"],
    colors: ["Classic Khaki", "Cloud Grey", "Navy", "Olive"],
    styles: ["smart_casual", "formal"],
    material: "98% Combed Cotton, 2% Elastane Wrinkle-Free",
    description: "Smart wrinkle-resistant dress chinos with flexible waistband for business meetings and weekend dining."
  },
  {
    id: "bottom-05",
    brand: "Diesel",
    name: "Diesel D-Strukt Slim Fit Distressed Jeans",
    category: "bottoms",
    price: 175.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 110,
    stock: 15,
    sizes: ["30x32", "32x32", "34x32"],
    colors: ["Washed Light Blue", "Acid Grey"],
    styles: ["streetwear"],
    material: "Italian Stretch Cotton Blend",
    description: "Rock-and-roll contemporary slim denim with subtle hand-finished whiskering and micro-distressing."
  },
  {
    id: "bottom-06",
    brand: "Carhartt WIP",
    name: "Carhartt WIP Aviation Tactical Cargo Pants",
    category: "bottoms",
    price: 135.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 230,
    stock: 20,
    sizes: ["S (30)", "M (32)", "L (34)", "XL (36)"],
    colors: ["Cypress Green", "Black Ripstop", "Camo Desert"],
    styles: ["streetwear"],
    material: "100% Columbia Heavy Ripstop Cotton",
    description: "Military-spec cargo trousers with reinforced knees, adjustable waist tabs, and leg drawstrings."
  },
  {
    id: "bottom-07",
    brand: "Zara",
    name: "Zara Pleated Wide-Leg Flowy Dress Trousers",
    category: "bottoms",
    price: 69.90,
    unit: "each",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    reviews: 140,
    stock: 22,
    sizes: ["EU 38 (30)", "EU 40 (32)", "EU 42 (34)"],
    colors: ["Charcoal Wool-Look", "Warm Sand", "Jet Black"],
    styles: ["smart_casual", "formal"],
    material: "Viscose Polyester Blend with Elegant Drape",
    description: "Modern tailored wide-leg trousers with front double pleats and side slant pockets."
  },
  {
    id: "bottom-08",
    brand: "AG Jeans",
    name: "AG Adriano Goldschmied Graduate Tailored Leg",
    category: "bottoms",
    price: 198.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1555689502-c4b22d76c56f?auto=format&fit=crop&w=500&q=80",
    rating: 5.0,
    reviews: 95,
    stock: 12,
    sizes: ["31x32", "32x32", "33x32", "34x32"],
    colors: ["Sulfur Midnight Blue", "Faded Raw Umber"],
    styles: ["smart_casual", "sustainable"],
    material: "360-Degree Premium Italian Luxury Stretch Denim",
    description: "Ultra-premium denim with slim mid-rise waist and clean tapered leg crafted in Los Angeles."
  },
  {
    id: "bottom-09",
    brand: "Uniqlo",
    name: "Uniqlo Smart Ankle Pants (2-Way Stretch)",
    category: "bottoms",
    price: 49.90,
    unit: "each",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 380,
    stock: 45,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy Grid", "Dark Heather Grey", "Black"],
    styles: ["smart_casual", "formal"],
    material: "Two-Way Stretch Polyester Rayon",
    description: "Clean cropped ankle cut with elastic hidden waistband that looks sharp with sneakers or loafers."
  },
  {
    id: "bottom-10",
    brand: "G-Star RAW",
    name: "G-Star RAW 3D 5620 Motion Tapered Jeans",
    category: "bottoms",
    price: 160.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1511196030310-7212eb127027?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 115,
    stock: 16,
    sizes: ["30x32", "32x32", "34x32"],
    colors: ["Dark Aged Denim", "Cobler Black"],
    styles: ["streetwear"],
    material: "Elwood 3D Ergonomic Engineered Denim",
    description: "Engineered 3D construction with knee patches, heel guards, and angled thigh seams."
  },
  {
    id: "bottom-11",
    brand: "Nike",
    name: "Nike Sportswear Tech Fleece Jogger Pants",
    category: "bottoms",
    price: 110.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 510,
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Heather Grey", "Triple Black", "Khaki"],
    styles: ["athletic", "streetwear"],
    material: "Lightweight Thermal Tech Fleece",
    description: "Tapered athletic joggers with bonded zipper storage pocket and ribbed ankle cuffs."
  },

  // ==========================================
  // 3. SHOES & SNEAKERS (11 Products)
  // ==========================================
  {
    id: "shoe-01",
    brand: "Nike",
    name: "Nike Air Max 90 Premium Sneakers",
    category: "footwear",
    price: 130.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 580,
    stock: 22,
    sizes: ["US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 12"],
    colors: ["Infrared / White / Black", "Triple White", "Black / Anthracite"],
    styles: ["streetwear", "athletic"],
    material: "Leather, Suede & Max Air Cushioning",
    description: "Legendary 90s silhouette featuring visible Max Air cushioning and waffle rubber outsole."
  },
  {
    id: "shoe-02",
    brand: "Adidas",
    name: "Adidas Samba Classic Leather Sneakers",
    category: "footwear",
    price: 100.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 640,
    stock: 28,
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["Cloud White / Core Black", "Core Black / White Gum"],
    styles: ["streetwear", "smart_casual"],
    material: "Full-Grain Leather with Suede T-Toe Overlay",
    description: "The global icon: timeless indoor football shoe with gum rubber sole and gold foil Samba branding."
  },
  {
    id: "shoe-03",
    brand: "New Balance",
    name: "New Balance 550 Retro Basketball Sneakers",
    category: "footwear",
    price: 119.99,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 410,
    stock: 20,
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["White / Green", "White / Navy", "Sea Salt Grey"],
    styles: ["streetwear", "smart_casual"],
    material: "Perforated Premium Leather",
    description: "Tribute to 1989 pro basketball heritage with low-top streamlined silhouette and durable traction."
  },
  {
    id: "shoe-04",
    brand: "On Running",
    name: "On Running Cloudmonster Max Cushion Running Shoes",
    category: "footwear",
    price: 169.99,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 320,
    stock: 16,
    sizes: ["US 8.5", "US 9", "US 10", "US 10.5", "US 11"],
    colors: ["All Black", "Frost / Cobalt", "Acai / Lavender"],
    styles: ["athletic"],
    material: "Helion Superfoam & CloudTec Pods",
    description: "Monster cushioning and explosive rebound powered by the radical Speedboard and Helion superfoam."
  },
  {
    id: "shoe-05",
    brand: "Timberland",
    name: "Timberland 6-Inch Premium Waterproof Nubuck Boots",
    category: "footwear",
    price: 198.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 550,
    stock: 15,
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["Wheat Yellow Nubuck", "Stealth Black"],
    styles: ["streetwear", "outdoor"],
    material: "Waterproof PrimaLoft Insulated Nubuck Leather",
    description: "The original yellow boot crafted with seam-sealed waterproof construction and anti-fatigue footbeds."
  },
  {
    id: "shoe-06",
    brand: "Dr. Martens",
    name: "Dr. Martens 1460 Smooth Leather 8-Eye Boots",
    category: "footwear",
    price: 170.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 490,
    stock: 18,
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    colors: ["Smooth Black", "Cherry Red"],
    styles: ["streetwear"],
    material: "Iconic AirWair Bouncing Sole Leather",
    description: "Eight-eyelet boot built with Goodyear welt, yellow welt stitching, and grooved air-cushioned soles."
  },
  {
    id: "shoe-07",
    brand: "Clarks Originals",
    name: "Clarks Originals Suede Desert Boots",
    category: "footwear",
    price: 150.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 275,
    stock: 20,
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    colors: ["Oak Suede", "Beeswax Leather", "Black Suede"],
    styles: ["smart_casual", "formal"],
    material: "English Suede with Natural Crepe Sole",
    description: "Designed in 1949 by Nathan Clark: clean lines, simple lace fastening, and signature crepe sole."
  },
  {
    id: "shoe-08",
    brand: "Vans",
    name: "Vans Old Skool Suede & Canvas Skate Shoes",
    category: "footwear",
    price: 70.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 620,
    stock: 35,
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["Black / White Side Stripe", "Navy / White", "Checkerboard"],
    styles: ["streetwear"],
    material: "Reinforced Suede & 10oz Canvas",
    description: "The classic skate shoe debuted in 1977 with the iconic leather side stripe and waffle rubber sole."
  },
  {
    id: "shoe-09",
    brand: "Converse",
    name: "Converse Chuck 70 Vintage High-Top",
    category: "footwear",
    price: 90.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 540,
    stock: 30,
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["Egret Parchment", "Classic Black", "Sunflower Yellow"],
    styles: ["streetwear", "smart_casual"],
    material: "12oz Organic Canvas with Ortholite Insole",
    description: "Enhanced vintage version of the all-star high-top with archival winged tongue stitching and thicker gloss foxing."
  },
  {
    id: "shoe-10",
    brand: "Heritage Craft",
    name: "Heritage Handcrafted Italian Leather Chelsea Boots",
    category: "footwear",
    price: 185.00,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 210,
    stock: 14,
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    colors: ["Cognac Tuscan Brown", "Midnight Black"],
    styles: ["smart_casual", "formal"],
    material: "Full-Grain Calfskin Leather",
    description: "Sleek ankle boot with elasticated side panels, rear pull tab, and cushioned leather insole."
  },
  {
    id: "shoe-11",
    brand: "Puma",
    name: "Puma Palermo Suede Terrace Sneakers",
    category: "footwear",
    price: 89.99,
    unit: "pair",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    reviews: 180,
    stock: 24,
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    colors: ["Cobalt Blue / White", "Archive White / Green"],
    styles: ["streetwear", "smart_casual"],
    material: "Suede Leather Upper & Gum Sole",
    description: "80s Italian terrace soccer classic revival with signature T-toe construction and gold Puma lettering."
  },

  // ==========================================
  // 4. BELTS & ACCESSORIES (11 Products)
  // ==========================================
  {
    id: "acc-01",
    brand: "Fossil",
    name: "Fossil Joe Genuine Leather Casual Jean Belt",
    category: "accessories",
    price: 45.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 240,
    stock: 30,
    sizes: ["32", "34", "36", "38", "40"],
    colors: ["Saddle Cognac Brown", "Dark Brown", "Black"],
    styles: ["smart_casual", "streetwear"],
    material: "100% Full-Grain Vegetable Tanned Leather",
    description: "Durable casual leather belt with vintage gunmetal roller buckle, designed for denim and chinos."
  },
  {
    id: "acc-02",
    brand: "Tommy Hilfiger",
    name: "Tommy Hilfiger Reversible Leather Dress Belt",
    category: "accessories",
    price: 52.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 310,
    stock: 25,
    sizes: ["32", "34", "36", "38"],
    colors: ["Black / Brown Reversible"],
    styles: ["formal", "smart_casual"],
    material: "100% Genuine Leather with Swivel Buckle",
    description: "Two-in-one reversible leather belt: easily twist the brushed silver buckle to switch between Black and Brown."
  },
  {
    id: "acc-03",
    brand: "Timberland",
    name: "Timberland Rugged Boot-Leather Heavy Belt",
    category: "accessories",
    price: 42.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 190,
    stock: 28,
    sizes: ["34", "36", "38", "40"],
    colors: ["Wheat Tan", "Dark Brown"],
    styles: ["streetwear", "smart_casual"],
    material: "Heavy-Duty Full Grain Nubuck",
    description: "Rugged heavy-duty work belt with antiqued brass single-prong buckle and embossed tree logo."
  },
  {
    id: "acc-04",
    brand: "Calvin Klein",
    name: "Calvin Klein Feather Edge Formal Dress Belt",
    category: "accessories",
    price: 49.50,
    unit: "each",
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    reviews: 155,
    stock: 22,
    sizes: ["32", "34", "36", "38"],
    colors: ["Sleek Black", "Deep Mahogany"],
    styles: ["formal", "smart_casual"],
    material: "Polished Italian Leather",
    description: "Sophisticated formal belt with stitched feathered edges and polished nickel buckle."
  },
  {
    id: "acc-05",
    brand: "Ray-Ban",
    name: "Ray-Ban Classic Aviator Polarized Sunglasses",
    category: "accessories",
    price: 175.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 520,
    stock: 20,
    sizes: ["Standard 58mm"],
    colors: ["Gold Frame / G-15 Green Lens", "Black Frame / Polarized Grey"],
    styles: ["smart_casual", "streetwear"],
    material: "Metal Frame & Crystal Polarized Lenses",
    description: "The original aviator sunglasses created for US aviators in 1937 with 100% UV400 protection."
  },
  {
    id: "acc-06",
    brand: "Seiko",
    name: "Seiko 5 Sports Automatic Steel Watch",
    category: "accessories",
    price: 260.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=500&q=80",
    rating: 5.0,
    reviews: 340,
    stock: 14,
    sizes: ["42.5mm Case"],
    colors: ["Sunray Blue Dial", "Matte Black Dial"],
    styles: ["smart_casual", "formal", "streetwear"],
    material: "Stainless Steel & Automatic Caliber 4R36",
    description: "Legendary Japanese automatic timepiece with 41-hour power reserve, day-date window, and 100m water resistance."
  },
  {
    id: "acc-07",
    brand: "Herschel",
    name: "Herschel Little America Classic 25L Backpack",
    category: "accessories",
    price: 110.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 390,
    stock: 18,
    sizes: ["25L (16-inch Laptop)"],
    colors: ["Navy / Tan Leather Straps", "All Black", "Raven Crosshatch"],
    styles: ["streetwear", "smart_casual"],
    material: "EcoSystem 600D Recycled Fabric",
    description: "Mountaineering-inspired daily backpack with padded fleece laptop compartment and magnetic strap closures."
  },
  {
    id: "acc-08",
    brand: "Carhartt WIP",
    name: "Carhartt WIP Acrylic Watch Beanie Hat",
    category: "accessories",
    price: 28.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 670,
    stock: 45,
    sizes: ["One Size"],
    colors: ["Hamilton Brown", "Black", "Dark Navy", "Grey Heather"],
    styles: ["streetwear"],
    material: "100% Stretchable Rib-Knit Acrylic",
    description: "Streetwear essential warm rib-knit beanie with woven square Carhartt label on cuff."
  },
  {
    id: "acc-09",
    brand: "Fossil",
    name: "Fossil Townsman Chronograph Leather Watch",
    category: "accessories",
    price: 160.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 210,
    stock: 16,
    sizes: ["44mm Case"],
    colors: ["Amber Dial / Dark Brown Leather", "Black / Black Leather"],
    styles: ["smart_casual", "formal"],
    material: "Stainless Steel & Rich Leather Strap",
    description: "Vintage-inspired chronograph watch with dual stopwatch subdials and Roman numeral hour markers."
  },
  {
    id: "acc-10",
    brand: "Montblanc Style",
    name: "Sartorial Slim Italian Leather Cardholder",
    category: "accessories",
    price: 65.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=500&q=80",
    rating: 4.9,
    reviews: 145,
    stock: 25,
    sizes: ["Slim (6 Cards + Cash Slot)"],
    colors: ["Saffiano Black", "Deep Navy"],
    styles: ["formal", "smart_casual"],
    material: "Saffiano Scratch-Resistant Calfskin",
    description: "Ultra-compact RFID-blocking card case with 6 card slots and center cash compartment."
  },
  {
    id: "acc-11",
    brand: "Ray-Ban",
    name: "Ray-Ban Clubmaster Classic Acetate Sunglasses",
    category: "accessories",
    price: 163.00,
    unit: "each",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    reviews: 380,
    stock: 22,
    sizes: ["Standard 49mm"],
    colors: ["Mock Tortoise / Arista Gold", "Black / Silver"],
    styles: ["streetwear", "smart_casual"],
    material: "Premium Acetate with Classic B-15 Glass",
    description: "Retro 1950s browline silhouette favored by cultural icons and musicians worldwide."
  }
];

export const BRANDS_LIST = [
  "All Brands",
  "Ralph Lauren",
  "Nike",
  "Adidas",
  "Levi's",
  "Zara",
  "New Balance",
  "On Running",
  "Fossil",
  "Timberland",
  "Ray-Ban",
  "Tommy Hilfiger",
  "Patagonia",
  "Uniqlo",
  "Carhartt WIP",
  "Lululemon",
  "Calvin Klein",
  "Seiko",
  "Clarks Originals",
  "Vans",
  "Converse",
  "Dr. Martens"
];

export const PROMO_CODES = {
  "FASHION20": {
    code: "FASHION20",
    discountPercent: 20,
    description: "20% off all designer clothes, sneakers, and accessories"
  },
  "SNEAKER10": {
    code: "SNEAKER10",
    discountPercent: 10,
    description: "10% instant discount on premium footwear"
  },
  "FREESHIP": {
    code: "FREESHIP",
    discountAmount: 9.99,
    description: "Free express courier shipping on orders over $75"
  }
};
